//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstudioCapra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato
    {
        public int ContratoId { get; set; }
        public int ClienteId { get; set; }
        public int ServicioId { get; set; }
        public decimal Costo { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public decimal Saldo { get; set; }
        public System.DateTime FechaCalculoSaldo { get; set; }
    
        public virtual Servicio Servicio { get; set; }
    }
}
