//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstudioCapra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratoEmpleado
    {
        public int Id { get; set; }
        public string Tipo { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public decimal Salario { get; set; }
        public string ModoDePago { get; set; }
        public System.DateTime DiaDePago { get; set; }
        public Nullable<int> EmpleadoId { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
