//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstudioCapra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public Empleado()
        {
            this.ContratoEmpleadoes = new HashSet<ContratoEmpleado>();
            this.TareaEmpleadoes = new HashSet<TareaEmpleado>();
        }
    
        public int EmpleadoId { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Especializacion { get; set; }
        public int ContratoId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual ICollection<ContratoEmpleado> ContratoEmpleadoes { get; set; }
        public virtual ICollection<TareaEmpleado> TareaEmpleadoes { get; set; }
    }
}
