//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstudioCapra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etapa
    {
        public Etapa()
        {
            this.EtapaObjectoMultimedias = new HashSet<EtapaObjectoMultimedia>();
            this.EtapaRecursoFisicoes = new HashSet<EtapaRecursoFisico>();
            this.EtapaServicios = new HashSet<EtapaServicio>();
            this.EtapaTareas = new HashSet<EtapaTarea>();
        }
    
        public int EtapaId { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
    
        public virtual ICollection<EtapaObjectoMultimedia> EtapaObjectoMultimedias { get; set; }
        public virtual ICollection<EtapaRecursoFisico> EtapaRecursoFisicoes { get; set; }
        public virtual ICollection<EtapaServicio> EtapaServicios { get; set; }
        public virtual ICollection<EtapaTarea> EtapaTareas { get; set; }
    }
}
