//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstudioCapra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EtapaRecursoFisico
    {
        public int EtapaId { get; set; }
        public long Id { get; set; }
        public int RecursoId { get; set; }
        public string Status { get; set; }
        public Nullable<int> RecursoFisicoId { get; set; }
    
        public virtual Etapa Etapa { get; set; }
        public virtual RecursoFisico RecursoFisico { get; set; }
    }
}
