//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstudioCapra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMenu
    {
        public int ItemMenuId { get; set; }
        public string Name { get; set; }
        public int Orden { get; set; }
        public bool Estado { get; set; }
        public int ItemMenuPadreId { get; set; }
        public string Controlador { get; set; }
        public string Accion { get; set; }
        public string Parametros { get; set; }
    }
}
