//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstudioCapra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjetoMultimedia
    {
        public ObjetoMultimedia()
        {
            this.EtapaObjectoMultimedias = new HashSet<EtapaObjectoMultimedia>();
        }
    
        public int ObjetoMultimediaId { get; set; }
        public string Servidor { get; set; }
        public string Directorio { get; set; }
        public string Nombre { get; set; }
        public string Tipo { get; set; }
        public byte[] DatosComprimidos { get; set; }
    
        public virtual ICollection<EtapaObjectoMultimedia> EtapaObjectoMultimedias { get; set; }
    }
}
