//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstudioCapra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecursoFisico
    {
        public RecursoFisico()
        {
            this.EtapaRecursoFisicoes = new HashSet<EtapaRecursoFisico>();
        }
    
        public int RecursoFisicoId { get; set; }
        public int TipoRecursoId { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaAdquisicion { get; set; }
        public Nullable<System.DateTime> FechaFinGarantia { get; set; }
        public string Especificaciones { get; set; }
        public Nullable<int> TipoRecursoFisicoId { get; set; }
    
        public virtual ICollection<EtapaRecursoFisico> EtapaRecursoFisicoes { get; set; }
    }
}
