//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstudioCapra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol
    {
        public Rol()
        {
            this.RoleMenus = new HashSet<RoleMenu>();
            this.UsuarioRols = new HashSet<UsuarioRol>();
        }
    
        public int RolId { get; set; }
        public string Status { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<RoleMenu> RoleMenus { get; set; }
        public virtual ICollection<UsuarioRol> UsuarioRols { get; set; }
    }
}
