//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstudioCapra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        public Servicio()
        {
            this.Contratoes = new HashSet<Contrato>();
        }
    
        public int ServicioId { get; set; }
        public int TipoServicioId { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Contrato> Contratoes { get; set; }
        public virtual TipoServicio TipoServicio { get; set; }
    }
}
