//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstudioCapra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TareaEmpleado
    {
        public long id { get; set; }
        public int TareaId { get; set; }
        public int EmpleadoId { get; set; }
        public string Status { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
