//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstudioCapra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoTarea
    {
        public TipoTarea()
        {
            this.Tareas = new HashSet<Tarea>();
        }
    
        public int TipoTareaId { get; set; }
        public string Nombre { get; set; }
        public string TareaTemplate { get; set; }
    
        public virtual ICollection<Tarea> Tareas { get; set; }
    }
}
