//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstudioCapra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoRecursoFisico
    {
        public int TipoRecursoFisicoId { get; set; }
        public string Nombre { get; set; }
        public string Atributo1 { get; set; }
        public string Atributo2 { get; set; }
        public string Atrbuto3 { get; set; }
        public string Atributo4 { get; set; }
        public string Atributo5 { get; set; }
    }
}
